Mobile 4331
moodlemobile/cordova-plugin-statusbar pull request #1
Opened 2023-08-23 11:52 UTC by crazyserver

2023-08-31 09:35 UTC, dpalou requested changes

2023-08-31 09:35 UTC, dpalou commented on src/android/StatusBar.java
> +        if (Build.VERSION.SDK_INT < Build.VERSION_CODES.O || style.isEmpty()) return; // SDK 26
Is it needed to change the version? Before this change, this code worked in Android 6+. After your change it will only work in Android 8+

2023-08-31 09:35 UTC, dpalou commented on src/android/StatusBar.java
> +        if (Build.VERSION.SDK_INT < Build.VERSION_CODES.O || style.isEmpty()) return; // SDK 26
I searched it and the Color.luminance function is only available in API 26. IMO it'd be better to have a workaround for those versions, you can do something like:

```
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
    return Color.luminance(color) < 0.5;
}

// Fallback for older versions.
```

As for the fallback, this is the first result I found in Google and it doesn't use Color.luminance:

https://stackoverflow.com/a/16313099

2023-09-04 08:06 UTC, crazyserver commented on src/android/StatusBar.java
> +        if (Build.VERSION.SDK_INT < Build.VERSION_CODES.O || style.isEmpty()) return; // SDK 26
Rechecking the API , it needs v24 onwards if the parameter is an integer: https://developer.android.com/reference/android/graphics/Color#luminance(int)

2023-09-04 08:57 UTC, dpalou approved these changes

2023-09-04 08:57 UTC, merged